version: 2.1

workflows:
  git-commit-workflow:
    jobs:
      - checks

executors:
  node:
    docker:
      - image: circleci/node:12.22.1
    # Everything is faster in RAM!
    # https://support.circleci.com/hc/en-us/articles/360054908812-Speed-up-steps-using-a-RAM-disk
    working_directory: /mnt/ramdisk/project

orbs:
  codecov: codecov/codecov@3.1.1

commands:
  install-deps:
    steps:
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            - v1-yarn-deps
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  checks:
    executor: node
    steps:
      - checkout
      - install-deps
      - run:
          command: yarn --silent lint --format junit | tee test-reports/eslint.xml
          when: always
      - run:
          command: yarn --silent typecheck | yarn --silent run typescript-xunit-xml | tee test-reports/typescript.xml
          when: always
      - run:
          command: yarn test --coverage --testResultsProcessor jest-junit
          environment:
            JEST_JUNIT_OUTPUT_FILE: test-reports/jest.xml
      - codecov/upload
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports
