version: 2.1

workflows:
  git-commit-workflow:
    jobs:
      - checks

executors:
  node:
    docker:
      - image: cimg/node:20.11
    # Everything is faster in RAM!
    # https://support.circleci.com/hc/en-us/articles/360054908812-Speed-up-steps-using-a-RAM-disk
    working_directory: /mnt/ramdisk/project

orbs:
  codecov: codecov/codecov@3.1.1

commands:
  install-deps:
    steps:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps
      - run: npm ci install --no-audit
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  checks:
    executor: node
    steps:
      - checkout
      - install-deps
      - run:
          command: npm run lint-ci
          when: always
      - run:
          command: npm run typecheck
          when: always
      - run:
          command: npm run test-ci
          when: always
          environment:
            JEST_JUNIT_OUTPUT_FILE: test-reports/jest.xml
      - codecov/upload
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports
